name: Japan Notebook
favicon: null
layout_spectrum: 0.32046
typography_spectrum: 0.34016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#820917'
    - '#a6565e'
    - '#9c9c9c'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
