name: Japan Notebook
favicon: null
layout_spectrum: 0.95956
typography_spectrum: 0.50128
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#820917'
    - '#a6565e'
    - '#9c9c9c'
  brandStrength: 1
  lightness: 0.1786147567909211
  saturation: 0.8306814576499164
  rhythmicContrast: 0.9415125870145857
purpose: []
