name: Japan Notebook
favicon: null
layout_spectrum: 0.6593471893575042
typography_spectrum: 0.042507188161835074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.708272592164576
  lightness: 0.1786147567909211
  saturation: 0.8306814576499164
  rhythmicContrast: 0.9415125870145857
purpose: []
